baseurl = "https://kalyan.biswas.dev/"
title = "Kalyan Biswas"
theme = "hugo-coder"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Kalyan Biswas"
  info = "Full Stack Developer"
  description = "Kalyan's Portfolio"
  keywords = "blog,developer,personal"
  avatarurl = "https://avatars.githubusercontent.com/u/160340582"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2026

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 1
  url = "mailto:kalyan@biswas.dev"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 1
  url = "https://linkedin.com/in/kalyan-biswas/"
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/kalyan-biswas/"
[[params.social]]
  name = "Instagram"
  icon = "fa-brands fa-instagram fa-2x"
  weight = 1
  url = "https://instagram.com/_kalyan.biswas/"
[[params.social]]
  name = "X"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 1
  url = "https://x.com/aponbiswas101/"
# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
